version: "2"
services:
  # blog后端api
  blog-api:
    image: java:8
    container_name: blog-api
    networks:
      blog-net:
        aliases:
          - blog-api
    ports:
      - 8091:8091
    restart: always
    # 日志文件保存在宿主机, 开启访问宿主机权限
    privileged: true
    working_dir: /app
    volumes:
      - ./blog-api.jar:/app/app.jar
    command: java -jar app.jar
  # blog 前端
  blog-element:
    image: nginx
    container_name: blog-element
    networks:
      - blog-net
    ports:
      - 80:80
    restart: always
    privileged: true
    # 映射目录
    volumes:
      # 首页文件
      - ./blog-element/dist:/usr/share/nginx/html
      # 配置文件
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      # 日志文件
      - ./nginx/log:/var/log/nginx
networks:
  blog-net:
    driver: bridge